[package]
name = "btrs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_bencode = "^0.2.4"
serde = "^1.0.0"
serde_derive = "^1.0.0"
serde_bytes = "0.11.17"
anyhow = "1.0.98"
urlencoding = "2.1.3"
sha1 = "0.10.6"


